services:
  postgres:
    image: 'postgres:latest'
    container_name: 'tripmate-user-service-db'
    environment:
      - 'POSTGRES_DB=tripmate-user-service-db'
      - 'POSTGRES_PASSWORD=123456'
      - 'POSTGRES_USER=root'
    ports:
      - '5432:5432'