services:
  postgres:
    image: 'postgres:latest'
    container_name: 'tripmate-user-service-db'
    environment:
      - 'POSTGRES_DB=tripmate-user-service-db'
      - 'POSTGRES_PASSWORD=123456'
      - 'POSTGRES_USER=root'
    ports:
      - '5432:5432'
    volumes: 
      - user_service_tripmate_db_data:/var/lib/postgresql
    networks:
      - microservices-net
volumes:
  user_service_tripmate_db_data:

    
  